export {addBookmark, removeBookmark, moveBookmark, editBookmark} from './bookmarks/bookmarks.slice'
export { setModalActive } from './modal/modal.slice'
export { setDev } from './dev/dev.slice'
export {setStyle, toggleHiding, setCustomText} from './customStyles/customStyles.slice'
export {setDisplayedLink} from './displayedLink/displayedLink.slice'
export { setExtension } from './extension/extension.slice'
export {setBgSize, setBgFilter, setBgCustom} from './background/background.slice'
export { setLogo } from './logo/logo.slice'