export {addBookmark, removeBookmark, moveBookmark, editBookmark} from './bookmarks/bookmarks.slice'
export { setModalActive } from './modal/modal.slice'
export { setDev } from './dev/dev.slice'
export {setStyle, toggleHiding} from './customStyles/customStyles.slice'
export {setDisplayedLink} from './displayedLink/displayedLink.slice'
export {setExtension} from './extension/extension.slice'